on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2.1
    with:
      shield: moNa2_R rgbled_adapter
      board: seeeduino_xiao_ble
      extra-modules: |
        zmk-pmw3610-driver
